#!/bin/bash
# Wrapper script to run demo_data.py from inside the API container
# This ensures all Python dependencies are available

set -e

# Default values (can be overridden via environment variables)
CASE_ID="${DEMO_CASE:-demo_case}"
EVIDENCE_UID="${DEMO_EVIDENCE:-demo_evidence}"
EVENTS="${DEMO_EVENTS:-200000}"
ADMIN_USER="${ADMIN_USER:-admin}"
ADMIN_PASS="${ADMIN_PASS:-admin123}"
BASE_URL="${DM_API_BASE_URL:-http://localhost:8080}"

echo "Ingesting demo data..."
echo "  Case ID:      $CASE_ID"
echo "  Evidence:     $EVIDENCE_UID"
echo "  Events:       $EVENTS"
echo ""

# Create a temporary Python script that will run inside the container
docker-compose exec -T api uv run python -c "
import requests
import random
import string
from datetime import datetime, timedelta

def login(base_url, username, password):
    resp = requests.post(
        f'{base_url}/api/auth/login',
        json={'username': username, 'password': password},
        timeout=10,
    )
    resp.raise_for_status()
    return resp.json()['access_token']

def ensure_case(base_url, token, case_id, note):
    headers = {'Authorization': f'Bearer {token}'}
    resp = requests.post(
        f'{base_url}/api/cases',
        json={'case_id': case_id, 'note': note},
        headers=headers,
        timeout=10,
    )
    if resp.status_code == 409:
        print(f'[i] Case {case_id!r} already exists, reusing.')
        return
    resp.raise_for_status()
    print(f'[+] Case {case_id!r} created.')

def ensure_evidence(base_url, token, evidence_uid, case_id):
    headers = {'Authorization': f'Bearer {token}'}
    payload = {
        'evidence_uid': evidence_uid,
        'case_id': case_id,
        'local_path': f'/lake/{case_id}/evidences/{evidence_uid}/collector.zip',
    }
    resp = requests.post(
        f'{base_url}/api/evidences',
        json=payload,
        headers=headers,
        timeout=10,
    )
    if resp.status_code == 409:
        print(f'[i] Evidence {evidence_uid!r} already exists, reusing.')
        return
    resp.raise_for_status()
    print(f'[+] Evidence {evidence_uid!r} declared.')

def random_event(case_id, evidence_uid, max_minutes=1440):
    now = datetime.utcnow() - timedelta(minutes=random.randint(0, max_minutes))
    source = random.choice(['PROCESS_CREATE', 'NETWORK_CONNECTION', 'FILE_WRITE', 'REGISTRY_SET'])
    host = random.choice(['WKST-01', 'WKST-02', 'SRV-AD01'])
    username = random.choice(['alice', 'bob', 'charlie', 'SYSTEM'])
    tags = random.sample(
        ['execution', 'initial_access', 'lateral_movement', 'collection', 'exfiltration'],
        k=random.randint(1, 2),
    )
    message = f'{source} event generated by demo script {random.randint(1000,9999)}'
    return {
        'ts': now.isoformat() + 'Z',
        'source': source,
        'message': message,
        'host': host,
        'user': username,
        'tags': tags,
        'score': random.randint(1, 100),
        'case_id': case_id,
        'evidence_uid': evidence_uid,
        'raw': {'demo': True, 'rand': ''.join(random.choices(string.ascii_lowercase, k=6))},
    }

def ingest_events(base_url, token, case_id, evidence_uid, total, chunk_size=500):
    headers = {'Authorization': f'Bearer {token}'}
    sent = 0
    batch_index = 0
    while sent < total:
        batch = []
        for _ in range(min(chunk_size, total - sent)):
            batch.append(random_event(case_id, evidence_uid))
        resp = requests.post(
            f'{base_url}/api/events/ingest',
            json=batch,
            headers=headers,
            timeout=30,
        )
        resp.raise_for_status()
        sent += len(batch)
        batch_index += 1
        print(f'[+] Batch {batch_index}: inserted {len(batch)} events (total {sent}/{total})')

# Main execution
# Use localhost since we're running inside the API container
base_url = 'http://localhost:8000'
case_id = '$CASE_ID'
evidence_uid = '$EVIDENCE_UID'
events = $EVENTS

print('[1/4] Logging in...')
token = login(base_url, '$ADMIN_USER', '$ADMIN_PASS')
print('[✓] Authenticated')

print('[2/4] Ensuring case exists...')
ensure_case(base_url, token, case_id, 'Demo case seeded via script')

print('[3/4] Ensuring evidence exists...')
ensure_evidence(base_url, token, evidence_uid, case_id)

print('[4/4] Ingesting events...')
ingest_events(base_url, token, case_id, evidence_uid, events)

print('[✓] Demo data seeded successfully.')
"
