#!/usr/bin/env python
"""
Bootstrap script to simulate case creation, evidence registration, and bulk event ingestion.

Usage:
    DM_ADMIN_USER=admin DM_ADMIN_PASS=admin123 python scripts/demo_data.py \
        --case-id demo_case \
        --evidence demo_evidence \
        --events 500000000
"""
import argparse
import os
import random
import string
from datetime import datetime, timedelta

import requests


def parse_args():
    parser = argparse.ArgumentParser(description="Seed a case, evidence, and thousands of events.")
    parser.add_argument("--base-url", default=os.environ.get("DM_API_BASE_URL", "http://localhost:8080"),
                        help="API base URL (default: http://localhost:8080)")
    parser.add_argument("--admin-user", default=os.environ.get("DM_ADMIN_USER", "admin"),
                        help="Admin username (default: env DM_ADMIN_USER or 'admin')")
    parser.add_argument("--admin-pass", default=os.environ.get("DM_ADMIN_PASS", "admin123"),
                        help="Admin password (default: env DM_ADMIN_PASS or 'admin123')")
    parser.add_argument("--case-id", default="demo_case",
                        help="Case identifier to create/use")
    parser.add_argument("--case-note", default="Demo case seeded via script",
                        help="Note to attach to the case")
    parser.add_argument("--evidence-uid", default="demo_evidence",
                        help="Evidence UID to create/use")
    parser.add_argument("--events", type=int, default=2_000_000,
                        help="Number of synthetic events to ingest")
    parser.add_argument("--chunk-size", type=int, default=500,
                        help="Batch size for /api/events/ingest")
    parser.add_argument("--max-minutes", type=int, default=24 * 60,
                        help="Spread events over the last N minutes (default: 24h)")
    return parser.parse_args()


def login(base_url: str, username: str, password: str) -> str:
    resp = requests.post(
        f"{base_url}/api/auth/login",
        json={"username": username, "password": password},
        timeout=10,
    )
    resp.raise_for_status()
    token = resp.json()["access_token"]
    return token


def ensure_case(base_url: str, token: str, case_id: str, note: str):
    headers = {"Authorization": f"Bearer {token}"}
    resp = requests.post(
        f"{base_url}/api/cases",
        json={"case_id": case_id, "note": note},
        headers=headers,
        timeout=10,
    )
    if resp.status_code == 409:
        print(f"[i] Case '{case_id}' already exists, reusing.")
        return
    resp.raise_for_status()
    print(f"[+] Case '{case_id}' created.")


def ensure_evidence(base_url: str, token: str, evidence_uid: str, case_id: str):
    headers = {"Authorization": f"Bearer {token}"}
    payload = {
        "evidence_uid": evidence_uid,
        "case_id": case_id,
        "local_path": f"/lake/{case_id}/evidences/{evidence_uid}/collector.zip",
    }
    resp = requests.post(
        f"{base_url}/api/evidences",
        json=payload,
        headers=headers,
        timeout=10,
    )
    if resp.status_code == 409:
        print(f"[i] Evidence '{evidence_uid}' already exists, reusing.")
        return
    resp.raise_for_status()
    print(f"[+] Evidence '{evidence_uid}' declared.")


def random_event(case_id: str, evidence_uid: str, max_minutes: int) -> dict:
    now = datetime.utcnow() - timedelta(minutes=random.randint(0, max_minutes))
    source = random.choice(["PROCESS_CREATE", "NETWORK_CONNECTION", "FILE_WRITE"])
    host = random.choice(["WKST-01", "WKST-02", "SRV-AD01"])
    username = random.choice(["alice", "bob", "charlie", "SYSTEM"])
    tags = random.sample(
        ["execution", "initial_access", "lateral_movement", "collection", "exfiltration"],
        k=random.randint(1, 2),
    )
    message = f"{source} event generated by demo script {random.randint(1000,9999)}"
    return {
        "ts": now.isoformat() + "Z",
        "source": source,
        "message": message,
        "host": host,
        "user": username,
        "tags": tags,
        "score": random.randint(1, 100),
        "case_id": case_id,
        "evidence_uid": evidence_uid,
        "raw": {"demo": True, "rand": ''.join(random.choices(string.ascii_lowercase, k=6))},
    }


def ingest_events(base_url: str, token: str, case_id: str, evidence_uid: str, total: int, chunk_size: int, max_minutes: int):
    headers = {"Authorization": f"Bearer {token}"}
    sent = 0
    batch_index = 0
    while sent < total:
        batch = []
        for _ in range(min(chunk_size, total - sent)):
            batch.append(random_event(case_id, evidence_uid, max_minutes=max_minutes))
        resp = requests.post(
            f"{base_url}/api/events/ingest",
            json=batch,
            headers=headers,
            timeout=30,
        )
        resp.raise_for_status()
        sent += len(batch)
        batch_index += 1
        print(f"[+] Batch {batch_index}: inserted {len(batch)} events (total {sent}/{total})")


def main():
    args = parse_args()
    token = login(args.base_url, args.admin_user, args.admin_pass)
    ensure_case(args.base_url, token, args.case_id, args.case_note)
    ensure_evidence(args.base_url, token, args.evidence_uid, args.case_id)
    ingest_events(args.base_url, token, args.case_id, args.evidence_uid, args.events, args.chunk_size, args.max_minutes)
    print("[✓] Demo data seeded successfully.")


if __name__ == "__main__":
    main()
