"""Add multi-language support to custom_scripts

Revision ID: 0879ed3e0c27
Revises: 0d8c359bb4f1
Create Date: 2025-11-11 17:57:26.432468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0879ed3e0c27'
down_revision: Union[str, None] = '0d8c359bb4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)

    if 'custom_scripts' in inspector.get_table_names():
        columns = [c['name'] for c in inspector.get_columns('custom_scripts')]

        with op.batch_alter_table('custom_scripts', schema=None) as batch_op:
            # Add new columns only if they don't exist
            if 'language_version' not in columns:
                batch_op.add_column(sa.Column('language_version', sa.String(), nullable=False, server_default='3.11'))
            if 'additional_files' not in columns:
                batch_op.add_column(sa.Column('additional_files', sa.Text(), nullable=True))
            if 'build_command' not in columns:
                batch_op.add_column(sa.Column('build_command', sa.String(), nullable=True))
            if 'entry_point' not in columns:
                batch_op.add_column(sa.Column('entry_point', sa.String(), nullable=True))
            if 'timeout_seconds' not in columns:
                batch_op.add_column(sa.Column('timeout_seconds', sa.Integer(), nullable=False, server_default='300'))
            if 'memory_limit_mb' not in columns:
                batch_op.add_column(sa.Column('memory_limit_mb', sa.Integer(), nullable=False, server_default='512'))
            if 'cpu_limit' not in columns:
                batch_op.add_column(sa.Column('cpu_limit', sa.String(), nullable=True))

        # Remove server defaults
        with op.batch_alter_table('custom_scripts', schema=None) as batch_op:
            if 'language_version' not in columns:
                batch_op.alter_column('language_version', server_default=None)
            if 'timeout_seconds' not in columns:
                batch_op.alter_column('timeout_seconds', server_default=None)
            if 'memory_limit_mb' not in columns:
                batch_op.alter_column('memory_limit_mb', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_scripts', schema=None) as batch_op:
        batch_op.drop_column('cpu_limit')
        batch_op.drop_column('memory_limit_mb')
        batch_op.drop_column('timeout_seconds')
        batch_op.drop_column('entry_point')
        batch_op.drop_column('build_command')
        batch_op.drop_column('additional_files')
        batch_op.drop_column('language_version')

    # ### end Alembic commands ###
