"""Add case members table for sharing

Revision ID: a1b2c3d4e5f6
Revises: 0d8c359bb4f1
Create Date: 2025-01-XX XX:XX:XX.XXXXXX

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '0d8c359bb4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)

    # Only create case_members table if it doesn't exist
    if 'case_members' not in inspector.get_table_names():
        op.create_table('case_members',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('case_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('added_at_utc', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_case_members_id'), 'case_members', ['id'], unique=False)
        op.create_index(op.f('ix_case_members_case_id'), 'case_members', ['case_id'], unique=False)
        op.create_index(op.f('ix_case_members_user_id'), 'case_members', ['user_id'], unique=False)
        
        # Index unique pour éviter les doublons
        op.create_index('idx_case_member_unique', 'case_members', ['case_id', 'user_id'], unique=True)
        
        # Foreign keys avec CASCADE
        op.create_foreign_key(
            'fk_case_members_case_id',
            'case_members', 'cases',
            ['case_id'], ['case_id'],
            ondelete='CASCADE'
        )
        op.create_foreign_key(
            'fk_case_members_user_id',
            'case_members', 'users',
            ['user_id'], ['id'],
            ondelete='CASCADE'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)

    if 'case_members' in inspector.get_table_names():
        op.drop_table('case_members')
    # ### end Alembic commands ###

